# .github/workflows/deploy.yml
name: Deploy DUKE QAOS-AI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Generate packaging scripts
      run: |
        java -cp target/DUKEAi-1.0.0.jar com.devinroyal.dukeai.enhancements.ScriptGenerator \
          --platforms linux,macos,web
        
    - name: Security scan
      uses: github/codeql-action/analyze@v2
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dukeai-artifacts
        path: |
          target/DUKEAi-1.0.0.jar
          target/scripts/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: dukeai-artifacts
        
    - name: Deploy to production
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f k8s/
        kubectl set image deployment/duke-qaos-ai duke-qaos-ai=ghcr.io/your-org/dukeai:latest
        kubectl rollout status deployment/duke-qaos-ai