# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duke-qaos-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: duke-qaos-ai
  template:
    metadata:
      labels:
        app: duke-qaos-ai
    spec:
      containers:
      - name: duke-qaos-ai
        image: duke-qaos-ai:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: duke-qaos-ai-service
spec:
  selector:
    app: duke-qaos-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer